/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/ping': {
    get: operations['APIController_getPing'];
  };
  '/api/v1/user': {
    get: operations['UsersController_currentUser'];
    /** User must be linked to a firebase ID */
    post: operations['UsersController_create'];
  };
  '/api/v1/house': {
    get: operations['HouseController_getHouse'];
    put: operations['HouseController_joinHouse'];
    post: operations['HouseController_create'];
  };
}

export interface components {
  schemas: {
    PingResponse: {
      /** Format: date-time */
      time: string;
      env: string;
    };
    CreateUserDto: {
      name: string;
      firebaseId: string;
    };
    UserResponseDto: {
      name: string;
      house?: string;
      firebaseId: string;
    };
    CreateHouseDto: {
      name: string;
      email: string;
      address: string;
    };
    HouseResponseDto: {
      name?: string;
      email?: string;
      address?: string;
      code: string;
      owner: string;
      users: components['schemas']['UserResponseDto'][];
    };
    JoinHouseDto: {
      houseCode: string;
    };
  };
}

export interface operations {
  APIController_getPing: {
    parameters: {};
    responses: {
      /** ping successful */
      200: {
        content: {
          'application/json': components['schemas']['PingResponse'];
        };
      };
    };
  };
  UsersController_currentUser: {
    parameters: {};
    responses: {
      /** returns the user information */
      200: {
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
    };
  };
  /** User must be linked to a firebase ID */
  UsersController_create: {
    parameters: {};
    responses: {
      /** User successfully created */
      201: {
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
      /** User already exists */
      409: unknown;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto'];
      };
    };
  };
  HouseController_getHouse: {
    parameters: {};
    responses: {
      /** house retrieved successfully */
      200: {
        content: {
          'application/json': components['schemas']['HouseResponseDto'];
        };
      };
      /** user is not in a house */
      204: never;
    };
  };
  HouseController_joinHouse: {
    parameters: {};
    responses: {
      /** house joined successfully */
      200: {
        content: {
          'application/json': components['schemas']['HouseResponseDto'];
        };
      };
      /** code is invalid */
      400: unknown;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JoinHouseDto'];
      };
    };
  };
  HouseController_create: {
    parameters: {};
    responses: {
      /** house created successfully */
      201: {
        content: {
          'application/json': components['schemas']['HouseResponseDto'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateHouseDto'];
      };
    };
  };
}

export interface external {}
