name: Deployment
on:
  push

jobs:
  frontend:
    name: Front-End
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: packages/frontend
        run: yarn install && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: flat-split
          channelId: live

  backend:
    name: Back-End
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "flat-share-api"
          heroku_email: "jcha686@aucklanduni.ac.nz"
          appdir: "packages/backend"
        env:
          HD_PING_TEXT: "prod"
          HD_DATABASE_URL: ${{secrets.DATABASE_URI}}
          HD_FIREBASE_SERVICE_ACCOUNT: ${{secrets.FIREBASE_KEY}}
          HD_PORT: 80
