name: Deployment
on:
  push

jobs:
  backend:
    name: Back-End
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "flat-share-api"
          heroku_email: "jcha686@aucklanduni.ac.nz"
          appdir: "packages/backend"
        env:
          PING_TEXT: "prod"
          DATABASE_URI: ${{secrets.DATABASE_URI}}
          PORT: 80
